name: Build APK FINAL FIXED

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libffi-dev libssl-dev libtool autoconf automake libncurses6 libncursesw6 openjdk-17-jdk unzip zip ccache pkg-config python3-dev libgmp-dev libmpfr-dev libmpc-dev
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 flask

      - name: Build with Buildozer
        run: |
          # Eski xatoli keshni tozalash
          rm -rf .buildozer
          # Buildozer git-ni ko'rishi uchun PATH
          export PATH=$PATH:/usr/bin/git
          buildozer -v android debug
        env:
          PATH: $PATH:/usr/bin:/usr/local/bin

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pubg-injector-apk
          path: bin/*.apk
